const tutorRoutes = {
  signup: "/tutors/register",
  verify: "/tutors/verify",
  login: "/tutors/login",
  googleUse: "/tutors/googleTutorIN",
  resendOtp: "/tutors/resendOTP",
  forgotPasswordEmail: "/tutors/forgotPassEmail",
  forgotOtpVerify: "/tutors/forgotOTPverify",
  forgotPassReset: "/tutors/forgotPasswordSave",
  dashobordPage: "/tutors/dashboardPage",
  basicInfoUpload: "/tutors/basicInfoUpload",
  getAllCategories: "/tutors/getAllCategories",
  getInstructorCourses: "/tutors/getInstructorCourses",
  getCourseView: "/tutors/getCourseView",
  uploadingCuricculum: "/tutors/uploadCuricculum",
  getViewCourse: "/tutors/getViewCourse",
  fetchtutorData: "/tutors/fetchtutorData",
  profileDetailSave: "/tutors/profileDataSave",
  msgsFetching: "/tutors/storedMsgsFetching",
  coursesForAssignment: "/tutors/coursesForAssignment",
  uploadAssignment: "/tutors/uploadingAssignment",
  assignmentsFetch: "/tutors/assignmentsFetch",
  reviewsFetch: "/tutors/reviewsFetch",
  fetchAssignments: "/tutors/fetchAssignments",
  getInstructor: "/tutors/getInstructor",
  fetchDashboardData: "/tutors/fetchDashboardData",
  courseGrowth: "/tutors/getCourseGrowth",
  updateProfileImg: "/tutors/updateProfileImg",
  sendInstructorMsg: "/tutors/sendInstructorMsg",
  getInitialMsg: "/tutors/getInitialMsg",
  updatePassword: "/tutors/updatePassword",
};

export default tutorRoutes;
